# travis config for Artus
sudo: required
language: cpp
services: docker
notifications:
  email:
    on_success: change
    on_failure: always
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
before_install:
  - sudo apt-get -y install libboost1.54-all-dev root-system
  - export KAPPAPATH=../Kappa
  - cd ..
  - git clone https://github.com/KappaAnalysis/Kappa.git -b CMSSW_7_6_X
  - make -C Kappa/DataFormats/test
  - git clone https://github.com/KappaAnalysis/KappaTools.git
  - cd KappaTools
  - cmake .
  - make -j2
  - cd ..
  - wget http://www-ekp.physik.uni-karlsruhe.de/~sieber/CondFormats.tar.gz
  - tar xzf CondFormats.tar.gz
  - cd Artus
install: 
  - cmake .
  - make VERBOSE=1
script: 
  - ./artus_core_test
