# travis config for Artus
sudo: required
language: cpp
services: docker
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_install:
  - sudo apt-get -y install libboost1.54-all-dev root-system
  - BASE=$(cd .. && echo $PWD)
  - cd ..
  - git clone https://github.com/KappaAnalysis/Kappa.git
  - make -C Kappa/DataFormats/test
  - git clone https://github.com/KappaAnalysis/KappaTools.git
  - make -C KappaTools
  - wget http://www-ekp.physik.uni-karlsruhe.de/~sieber/CondFormats.tar.gz
  - tar xzf CondFormats.tar.gz
  - cd Artus
install: 
  - cmake .
  - make VERBOSE=1
script: 
  - ./artus_core_test
